# Improves the readability of connection labels
(** -> **)[*].style.font-size: 20
(** -> **)[*].style.font-color: '#404040'

(** <- **)[*].style.font-size: 20
(** <- **)[*].style.font-color: '#404040'
